spring:
  application:
    name: app

  datasource:
    url: jdbc:postgresql://localhost:5432/uber
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver

  jpa:
    showSql: true
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
#        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        format_sql: true
    defer-datasource-initialization: true
  distance:
    base-url: http://router.project-osrm.org/route/v1/driving/

  sql:
    init:
      mode: always
    data-locations: classpath:data.sql

logging:
  level:
    org.springframework: DEBUG